$(document).ready(function(){
    $(".banner-carousel").owlCarousel({
        items:1,
        nav:true
    });
    $("latestImage").hover(function(){
        $(".readMore").addClass(".readMore2");
    });
});